name: newest_trl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.6.1=h59595ed_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=24.3.0=py310h06a4308_0
  - aws-c-auth=0.7.31=he1a10d6_2
  - aws-c-cal=0.7.4=hae4d56a_2
  - aws-c-common=0.9.29=hb9d3cd8_0
  - aws-c-compression=0.2.19=h2bff981_2
  - aws-c-event-stream=0.4.3=h19b0707_4
  - aws-c-http=0.8.10=h14a7884_2
  - aws-c-io=0.14.19=hc9e6898_1
  - aws-c-mqtt=0.10.7=hb8d5873_2
  - aws-c-s3=0.6.7=h666547d_0
  - aws-c-sdkutils=0.1.19=h2bff981_4
  - aws-checksums=0.1.20=h2bff981_1
  - aws-crt-cpp=0.28.3=hbe26082_8
  - aws-sdk-cpp=1.11.407=h25d6d5c_1
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - azure-storage-files-datalake-cpp=12.11.0=h325d260_1
  - bitsandbytes=0.45.5=cuda118_py310hda4ad70_0
  - blas=1.0=mkl
  - blas-devel=3.9.0=12_linux64_mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.4.26=py310h06a4308_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py310h06a4308_0
  - colorama=0.4.6=py310h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.8=py310h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - docstring_parser=0.16=py310h06a4308_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.17.0=py310h06a4308_0
  - fire=0.7.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.13.3=ha770c72_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - fsspec=2024.12.0=py310h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.84.1=h07242d1_0
  - glib-tools=2.84.1=h4833e2c_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.7.9=hb077bed_0
  - greenlet=3.1.1=py310h6a678d5_0
  - icu=75.1=he02047a_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=py310h06a4308_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarrow=17.0.0=had3b6fe_16_cpu
  - libarrow-acero=17.0.0=h5888daf_16_cpu
  - libarrow-dataset=17.0.0=h5888daf_16_cpu
  - libarrow-substrait=17.0.0=hf54134d_16_cpu
  - libblas=3.9.0=12_linux64_mkl
  - libboost=1.86.0=h6c02f8c_3
  - libboost-python=1.86.0=py310ha2bacc8_3
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=12_linux64_mkl
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.13.0=h332b0f4_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.29.0=h435de7b_0
  - libgoogle-cloud-storage=2.29.0=h0121fbd_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libparquet=17.0.0=h39682fd_16_cpu
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libprotobuf=4.25.3=hd5b35b9_1
  - librdkit=2025.03.1=h84b0b3c_0
  - libre2-11=2024.02.01=h2f2cdcf_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.20.0=h0e7cc3e_1
  - libtiff=4.7.0=hd9ff511_4
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h6a678d5_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h4bc477f_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py310h06a4308_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-devel=2021.4.0=h66538d2_640
  - mkl-include=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.1.0=py310h5eee18b_0
  - multiprocess=0.70.15=py310h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=py310h06a4308_0
  - numexpr=2.8.4=py310h8879344_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openblas=0.3.29=pthreads_h6ec200e_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.0=h7b32b05_0
  - orc=2.0.2=h669347b_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - peft=0.15.2=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h7e6dc6c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - propcache=0.3.1=py310h5eee18b_0
  - protobuf=4.25.3=py310he36ed58_1
  - psutil=5.9.0=py310h5eee18b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=17.0.0=py310hb7f781d_2
  - pyarrow-core=17.0.0=py310hac404ae_2_cpu
  - pycairo=1.23.0=py310hd1222b9_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.17=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py310h5eee18b_0
  - python_abi=3.10=7_cp310
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - qhull=2020.2=h434a139_5
  - rdkit=2025.03.1=py310hcd13295_0
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.2=h8c095d6_2
  - regex=2024.11.6=py310h5eee18b_0
  - reportlab=3.5.67=py310h0edfc0f_1
  - requests=2.32.3=py310h06a4308_1
  - rich=13.9.4=py310h06a4308_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - s2n=1.5.5=h3931f03_0
  - safetensors=0.5.3=py310h922eef2_0
  - scipy=1.10.1=py310hd5efca6_0
  - setuptools=72.1.0=py310h06a4308_0
  - shtab=1.7.2=pyhd8ed1ab_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlalchemy=2.0.37=py310h00e1ef3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - termcolor=2.1.0=py310h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typeguard=4.2.1=py310h06a4308_0
  - typing=3.10.0.0=py310h06a4308_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tyro=0.9.19=pyhd8ed1ab_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.3.0=py310h06a4308_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.43=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xxhash=0.8.0=h7f8727e_3
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.3.0
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - blake3==1.0.4
      - cachetools==5.5.2
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.3
      - coverage==7.8.0
      - cupy-cuda12x==13.4.1
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - deepspeed==0.16.7
      - deprecated==1.2.18
      - depyf==0.18.0
      - diffusers==0.33.1
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - execnet==2.1.1
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - flash-attn==2.7.4.post1
      - gguf==0.16.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.31.1
      - immutables==0.20
      - importlib-metadata==8.0.0
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - liger-kernel==0.5.8
      - llguidance==0.7.19
      - llm-blender==0.0.2
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - marshmallow==3.26.1
      - mergekit==0.0.6
      - mistral-common==1.5.4
      - msgpack==1.1.0
      - msgspec==0.19.0
      - mypy-extensions==1.1.0
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.77.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.5
      - outlines==0.1.11
      - outlines-core==0.1.26
      - parameterized==0.9.0
      - partial-json-parser==0.2.1.1.post5
      - pfzy==0.3.4
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - pytest-rerunfailures==15.0
      - pytest-xdist==3.6.1
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - ray==2.45.0
      - referencing==0.36.2
      - rich-toolkit==0.14.4
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - transformers==4.51.3
      - triton==3.2.0
      - trl==0.18.0.dev0
      - typer==0.15.3
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - vllm==0.8.5.post1
      - wandb==0.19.10
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
prefix: /home/ccao2/.conda/envs/newest_trl
